spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: users-routes
          uri: lb://users
          predicates:
            - Path=/commerce/users/**
          filters:
            - RewritePath=/commerce/users/(?<segment>.*), /${segment}
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true 
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/


server:
  port: 8080
